//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSL_Test__1 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class SettingsFile : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsFile defaultInstance = ((SettingsFile)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsFile())));
        
        public static SettingsFile Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ArtistFlip {
            get {
                return ((bool)(this["ArtistFlip"]));
            }
            set {
                this["ArtistFlip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteZipFiles {
            get {
                return ((bool)(this["DeleteZipFiles"]));
            }
            set {
                this["DeleteZipFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uTorrent.exe")]
        public string TorrentClient {
            get {
                return ((string)(this["TorrentClient"]));
            }
            set {
                this["TorrentClient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\uTorrent")]
        public string TorrentClientFolder {
            get {
                return ((string)(this["TorrentClientFolder"]));
            }
            set {
                this["TorrentClientFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TorrentSaveFolder {
            get {
                return ((string)(this["TorrentSaveFolder"]));
            }
            set {
                this["TorrentSaveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DownloadFolder {
            get {
                return ((string)(this["DownloadFolder"]));
            }
            set {
                this["DownloadFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomDirectory {
            get {
                return ((string)(this["CustomDirectory"]));
            }
            set {
                this["CustomDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableNotifications {
            get {
                return ((bool)(this["DisableNotifications"]));
            }
            set {
                this["DisableNotifications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal AutoCheckTime {
            get {
                return ((decimal)(this["AutoCheckTime"]));
            }
            set {
                this["AutoCheckTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoCheck {
            get {
                return ((bool)(this["AutoCheck"]));
            }
            set {
                this["AutoCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UppercaseAllFolderNames {
            get {
                return ((bool)(this["UppercaseAllFolderNames"]));
            }
            set {
                this["UppercaseAllFolderNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LowercaseAllFolderNames {
            get {
                return ((bool)(this["LowercaseAllFolderNames"]));
            }
            set {
                this["LowercaseAllFolderNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RemoveDoubleSpaces {
            get {
                return ((bool)(this["RemoveDoubleSpaces"]));
            }
            set {
                this["RemoveDoubleSpaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TrackZipFiles {
            get {
                return ((bool)(this["TrackZipFiles"]));
            }
            set {
                this["TrackZipFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TrackTorrentFiles {
            get {
                return ((bool)(this["TrackTorrentFiles"]));
            }
            set {
                this["TrackTorrentFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%a\\%y - %t")]
        public string DownloadFormats {
            get {
                return ((string)(this["DownloadFormats"]));
            }
            set {
                this["DownloadFormats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Album:Album</string>
  <string>EP:EP</string>
  <string>Live:Live</string>
  <string>Single:Single</string>
  <string>Mixtape:Mixtape</string>
  <string>Remix:Remix</string>
  <string>Soundboard:Soundboard</string>
  <string>Compilation:Compilation</string>
  <string>Bootleg:Bootleg</string>
  <string>Interview:Interview</string>
  <string>Unknown:Unknown</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ReleaseFormatNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ReleaseFormatNames"]));
            }
            set {
                this["ReleaseFormatNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>VBR:V# (VBR)</string>
  <string>CBR:### (CBR)</string>
  <string>APX:APX (VBR)</string>
  <string>APS:APS (VBR)</string>
  <string>q8.x:q8.x(VBR)</string>
  <string>Lossless:Lossless</string>
  <string>24bitLossless:24bit Lossless</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BitrateNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BitrateNames"]));
            }
            set {
                this["BitrateNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MinimizeToTray {
            get {
                return ((bool)(this["MinimizeToTray"]));
            }
            set {
                this["MinimizeToTray"] = value;
            }
        }
    }
}
